version: '3.4'
services:
    minergate-cli:
        image: minecoins/minergate-cli
        networks:
            - minergate-cli-net
        deploy:
            replicas: 18
            update_config:
                parallelism: 6
            restart_policy:
                condition: on-failure
                
networks:
    minergate-cli-net:
