version: "3.4"

services:
  minergate-cli:
    image: minecoins/minergate-cli
    networks:
      - minergate-cli-net
    deploy:
      replicas: 7
      update_config:
        parallelism: 7
      restart_policy:
        condition: on-failure
    command: ["-user", "paul.grounded@gmail.com", "-xmr"]

networks:
  minergate-cli-net:
