version: "3"
services:

  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    stop_grace_period: 30s
    deploy:
      placement:
        constraints: [node.role == manager]
